services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 5173:5173
    volumes:
      - ./packages:/app/packages
      - /app/node_modules
    networks:
      - myguardcare_affiliates_network
    develop:
      watch:
        - action: sync
          path: ./apps/web/src
          target: /app/apps/web/src
          ignore:
            - node_modules/
            - build/
        - action: rebuild
          path: ./apps/web/package.json
  api:
    container_name: api
    environment:
      API_PORT: ${API_PORT}
      API_DB_USER: ${API_DB_USER}
      API_DB_PASSWORD: ${API_DB_PASSWORD}
      API_DB_HOST: ${API_DB_HOST}
      API_DB_PORT: ${API_DB_PORT}
      API_DB_NAME: ${API_DB_NAME}
      API_NODE_ENV: ${API_NODE_ENV}
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./packages:/app/packages
    networks:
      - myguardcare_affiliates_network
    depends_on:
      mongodb:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./apps/api/src
          target: /app/apps/api/src
          ignore:
            - node_modules/
            - build/
        - action: rebuild
          path: ./apps/api/package.json
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${API_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${API_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${API_DB_NAME}
    ports:
      - ${API_DB_PORT}:${API_DB_PORT}
    volumes:
      - mongodb_data:/data/db
    networks:
      - myguardcare_affiliates_network
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.runCommand({ ping: 1 })']
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  myguardcare_affiliates_network:
    driver: bridge

volumes:
  mongodb_data:
